FROM golang:1.25 AS builder

WORKDIR /build

COPY go.mod go.sum ./

RUN go mod download

COPY . .
RUN make build


FROM ubuntu:24.04

RUN useradd --create-home --shell /usr/sbin/nologin zenbpm

USER zenbpm

WORKDIR /home/zenbpm

COPY --from=builder --chown=zenbpm:zenbpm /build/zenbpm ./zenbpm
COPY --from=builder --chown=zenbpm:zenbpm /build/conf/zenbpm/conf-dev.yaml ./conf-dev.yaml

ENV PROFILE=DEV

ENV CONFIG_FILE=/home/zenbpm/conf-dev.yaml

ENTRYPOINT ["./zenbpm"]
