// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: flow_element_instance.sql

package sql

import (
	"context"
	"strings"
)

const countFlowElementInstances = `-- name: CountFlowElementInstances :one
SELECT
    count(*)
FROM
    flow_element_instance
WHERE
    process_instance_key = ?1
`

func (q *Queries) CountFlowElementInstances(ctx context.Context, processInstanceKey int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFlowElementInstances, processInstanceKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFlowElementInstance = `-- name: DeleteFlowElementInstance :exec
DELETE FROM flow_element_instance
WHERE process_instance_key IN (/*SLICE:keys*/?)
`

func (q *Queries) DeleteFlowElementInstance(ctx context.Context, keys []int64) error {
	query := deleteFlowElementInstance
	var queryParams []interface{}
	if len(keys) > 0 {
		for _, v := range keys {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:keys*/?", strings.Repeat(",?", len(keys))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:keys*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const findFlowElementInstances = `-- name: FindFlowElementInstances :many
SELECT
    fei."key", fei.element_id, fei.process_instance_key, fei.execution_token_key, fei.created_at, fei.input_variables, fei.output_variables,
    COUNT(*) OVER() AS total_count
FROM execution_token AS et
JOIN process_instance AS pi
    ON (pi.parent_process_execution_token = et.key
    OR pi.key = ?1)
    AND process_type != 3
JOIN flow_element_instance AS fei
    ON fei.process_instance_key = pi.key
WHERE
    et.process_instance_key = ?1
LIMIT ?3 OFFSET ?2
`

type FindFlowElementInstancesParams struct {
	ProcessInstanceKey int64 `json:"process_instance_key"`
	Offset             int64 `json:"offset"`
	Limit              int64 `json:"limit"`
}

type FindFlowElementInstancesRow struct {
	Key                int64  `json:"key"`
	ElementID          string `json:"element_id"`
	ProcessInstanceKey int64  `json:"process_instance_key"`
	ExecutionTokenKey  int64  `json:"execution_token_key"`
	CreatedAt          int64  `json:"created_at"`
	InputVariables     string `json:"input_variables"`
	OutputVariables    string `json:"output_variables"`
	TotalCount         int64  `json:"total_count"`
}

func (q *Queries) FindFlowElementInstances(ctx context.Context, arg FindFlowElementInstancesParams) ([]FindFlowElementInstancesRow, error) {
	rows, err := q.db.QueryContext(ctx, findFlowElementInstances, arg.ProcessInstanceKey, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindFlowElementInstancesRow{}
	for rows.Next() {
		var i FindFlowElementInstancesRow
		if err := rows.Scan(
			&i.Key,
			&i.ElementID,
			&i.ProcessInstanceKey,
			&i.ExecutionTokenKey,
			&i.CreatedAt,
			&i.InputVariables,
			&i.OutputVariables,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowElementInstanceByKey = `-- name: GetFlowElementInstanceByKey :one
SELECT
    "key", element_id, process_instance_key, execution_token_key, created_at, input_variables, output_variables
FROM
    flow_element_instance
WHERE
    key = ?1
`

func (q *Queries) GetFlowElementInstanceByKey(ctx context.Context, key int64) (FlowElementInstance, error) {
	row := q.db.QueryRowContext(ctx, getFlowElementInstanceByKey, key)
	var i FlowElementInstance
	err := row.Scan(
		&i.Key,
		&i.ElementID,
		&i.ProcessInstanceKey,
		&i.ExecutionTokenKey,
		&i.CreatedAt,
		&i.InputVariables,
		&i.OutputVariables,
	)
	return i, err
}

const getFlowElementInstanceByTokenKey = `-- name: GetFlowElementInstanceByTokenKey :one
SELECT
    "key", element_id, process_instance_key, execution_token_key, created_at, input_variables, output_variables
FROM
    flow_element_instance
WHERE
    execution_token_key = ?1
ORDER BY created_at DESC
`

func (q *Queries) GetFlowElementInstanceByTokenKey(ctx context.Context, executionTokenKey int64) (FlowElementInstance, error) {
	row := q.db.QueryRowContext(ctx, getFlowElementInstanceByTokenKey, executionTokenKey)
	var i FlowElementInstance
	err := row.Scan(
		&i.Key,
		&i.ElementID,
		&i.ProcessInstanceKey,
		&i.ExecutionTokenKey,
		&i.CreatedAt,
		&i.InputVariables,
		&i.OutputVariables,
	)
	return i, err
}

const getFlowElementInstances = `-- name: GetFlowElementInstances :many
SELECT
    "key", element_id, process_instance_key, execution_token_key, created_at, input_variables, output_variables,
    COUNT(*) OVER() AS total_count
FROM
    flow_element_instance
WHERE
    process_instance_key = ?1
LIMIT ?3 OFFSET ?2
`

type GetFlowElementInstancesParams struct {
	ProcessInstanceKey int64 `json:"process_instance_key"`
	Offset             int64 `json:"offset"`
	Limit              int64 `json:"limit"`
}

type GetFlowElementInstancesRow struct {
	Key                int64  `json:"key"`
	ElementID          string `json:"element_id"`
	ProcessInstanceKey int64  `json:"process_instance_key"`
	ExecutionTokenKey  int64  `json:"execution_token_key"`
	CreatedAt          int64  `json:"created_at"`
	InputVariables     string `json:"input_variables"`
	OutputVariables    string `json:"output_variables"`
	TotalCount         int64  `json:"total_count"`
}

func (q *Queries) GetFlowElementInstances(ctx context.Context, arg GetFlowElementInstancesParams) ([]GetFlowElementInstancesRow, error) {
	rows, err := q.db.QueryContext(ctx, getFlowElementInstances, arg.ProcessInstanceKey, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFlowElementInstancesRow{}
	for rows.Next() {
		var i GetFlowElementInstancesRow
		if err := rows.Scan(
			&i.Key,
			&i.ElementID,
			&i.ProcessInstanceKey,
			&i.ExecutionTokenKey,
			&i.CreatedAt,
			&i.InputVariables,
			&i.OutputVariables,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveFlowElementInstance = `-- name: SaveFlowElementInstance :exec
INSERT INTO flow_element_instance(key, element_id, process_instance_key, created_at, execution_token_key, input_variables, output_variables)
    VALUES (?, ? ,? ,?, ?, ?, ?)
ON CONFLICT
    DO UPDATE SET
       input_variables = excluded.input_variables
`

type SaveFlowElementInstanceParams struct {
	Key                int64  `json:"key"`
	ElementID          string `json:"element_id"`
	ProcessInstanceKey int64  `json:"process_instance_key"`
	CreatedAt          int64  `json:"created_at"`
	ExecutionTokenKey  int64  `json:"execution_token_key"`
	InputVariables     string `json:"input_variables"`
	OutputVariables    string `json:"output_variables"`
}

func (q *Queries) SaveFlowElementInstance(ctx context.Context, arg SaveFlowElementInstanceParams) error {
	_, err := q.db.ExecContext(ctx, saveFlowElementInstance,
		arg.Key,
		arg.ElementID,
		arg.ProcessInstanceKey,
		arg.CreatedAt,
		arg.ExecutionTokenKey,
		arg.InputVariables,
		arg.OutputVariables,
	)
	return err
}

const updateOutputFlowElementInstance = `-- name: UpdateOutputFlowElementInstance :exec
INSERT INTO flow_element_instance(key, element_id, process_instance_key, created_at, execution_token_key, input_variables, output_variables)
    VALUES (?, ? ,? ,?, ?, ?, ?)
ON CONFLICT
    DO UPDATE SET
       output_variables = excluded.output_variables
`

type UpdateOutputFlowElementInstanceParams struct {
	Key                int64  `json:"key"`
	ElementID          string `json:"element_id"`
	ProcessInstanceKey int64  `json:"process_instance_key"`
	CreatedAt          int64  `json:"created_at"`
	ExecutionTokenKey  int64  `json:"execution_token_key"`
	InputVariables     string `json:"input_variables"`
	OutputVariables    string `json:"output_variables"`
}

func (q *Queries) UpdateOutputFlowElementInstance(ctx context.Context, arg UpdateOutputFlowElementInstanceParams) error {
	_, err := q.db.ExecContext(ctx, updateOutputFlowElementInstance,
		arg.Key,
		arg.ElementID,
		arg.ProcessInstanceKey,
		arg.CreatedAt,
		arg.ExecutionTokenKey,
		arg.InputVariables,
		arg.OutputVariables,
	)
	return err
}
