// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: job.sql

package sql

import (
	"context"
	"database/sql"
	"strings"
)

const countWaitingJobs = `-- name: CountWaitingJobs :one
SELECT
    count(*)
FROM
    job
WHERE
    state = 1
`

func (q *Queries) CountWaitingJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWaitingJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProcessInstancesJobs = `-- name: DeleteProcessInstancesJobs :exec
DELETE FROM job
WHERE process_instance_key IN (/*SLICE:keys*/?)
`

func (q *Queries) DeleteProcessInstancesJobs(ctx context.Context, keys []int64) error {
	query := deleteProcessInstancesJobs
	var queryParams []interface{}
	if len(keys) > 0 {
		for _, v := range keys {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:keys*/?", strings.Repeat(",?", len(keys))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:keys*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const findActiveJobsByType = `-- name: FindActiveJobsByType :many
SELECT
    "key", element_instance_key, element_id, process_instance_key, type, state, created_at, variables, execution_token, assignee
FROM
    job
WHERE
    type = ?1
    AND state = 1
`

func (q *Queries) FindActiveJobsByType(ctx context.Context, type_ string) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, findActiveJobsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.Key,
			&i.ElementInstanceKey,
			&i.ElementID,
			&i.ProcessInstanceKey,
			&i.Type,
			&i.State,
			&i.CreatedAt,
			&i.Variables,
			&i.ExecutionToken,
			&i.Assignee,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllJobs = `-- name: FindAllJobs :many
SELECT
    "key", element_instance_key, element_id, process_instance_key, type, state, created_at, variables, execution_token, assignee
FROM
    job
LIMIT ?2 offset ?1
`

type FindAllJobsParams struct {
	Offset int64 `json:"offset"`
	Size   int64 `json:"size"`
}

func (q *Queries) FindAllJobs(ctx context.Context, arg FindAllJobsParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, findAllJobs, arg.Offset, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.Key,
			&i.ElementInstanceKey,
			&i.ElementID,
			&i.ProcessInstanceKey,
			&i.Type,
			&i.State,
			&i.CreatedAt,
			&i.Variables,
			&i.ExecutionToken,
			&i.Assignee,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findJobByJobKey = `-- name: FindJobByJobKey :one
SELECT
    "key", element_instance_key, element_id, process_instance_key, type, state, created_at, variables, execution_token, assignee
FROM
    job
WHERE
    key = ?1
`

func (q *Queries) FindJobByJobKey(ctx context.Context, key int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, findJobByJobKey, key)
	var i Job
	err := row.Scan(
		&i.Key,
		&i.ElementInstanceKey,
		&i.ElementID,
		&i.ProcessInstanceKey,
		&i.Type,
		&i.State,
		&i.CreatedAt,
		&i.Variables,
		&i.ExecutionToken,
		&i.Assignee,
	)
	return i, err
}

const findJobByKey = `-- name: FindJobByKey :one
SELECT
    "key", element_instance_key, element_id, process_instance_key, type, state, created_at, variables, execution_token, assignee
FROM
    job
WHERE
    key = ?1
`

func (q *Queries) FindJobByKey(ctx context.Context, key int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, findJobByKey, key)
	var i Job
	err := row.Scan(
		&i.Key,
		&i.ElementInstanceKey,
		&i.ElementID,
		&i.ProcessInstanceKey,
		&i.Type,
		&i.State,
		&i.CreatedAt,
		&i.Variables,
		&i.ExecutionToken,
		&i.Assignee,
	)
	return i, err
}

const findJobs = `-- name: FindJobs :many
SELECT
  j."key", j.element_instance_key, j.element_id, j.process_instance_key, j.type, j.state, j.created_at, j.variables, j.execution_token, j.assignee,
  COUNT(*) OVER() AS total_count
FROM job AS j
WHERE
  CAST(?1 AS TEXT) IS CAST(?1 AS TEXT)
  AND COALESCE(?2, type) = type
  AND COALESCE(?3, state) = state
  AND (CAST(?4 AS INTEGER) IS NULL OR j.process_instance_key = CAST(?4 AS TEXT)) 
  AND (CAST(?5 AS TEXT) IS NULL OR j.assignee = CAST(?5 AS TEXT)) 
  
ORDER BY
  CASE CAST(?1 AS TEXT) WHEN 'created_at_asc'  THEN j.created_at END ASC,
  CASE CAST(?1 AS TEXT) WHEN 'created_at_desc' THEN j.created_at END DESC,
  CASE CAST(?1 AS TEXT) WHEN 'key_asc' THEN j."key" END ASC,
  CASE CAST(?1 AS TEXT) WHEN 'key_desc' THEN j."key" END DESC,
  CASE CAST(?1 AS TEXT) WHEN 'type_asc' THEN j."type" END ASC,
  CASE CAST(?1 AS TEXT) WHEN 'type_desc' THEN j."type" END DESC,
  CASE CAST(?1 AS TEXT) WHEN 'state_asc' THEN j.state END ASC,
  CASE CAST(?1 AS TEXT) WHEN 'state_desc' THEN j.state END DESC,
  j."key" DESC

LIMIT ?7
OFFSET ?6
`

type FindJobsParams struct {
	Sort               sql.NullString `json:"sort"`
	Type               sql.NullString `json:"type"`
	State              sql.NullInt64  `json:"state"`
	ProcessInstanceKey sql.NullInt64  `json:"process_instance_key"`
	Assignee           sql.NullString `json:"assignee"`
	Offset             int64          `json:"offset"`
	Limit              int64          `json:"limit"`
}

type FindJobsRow struct {
	Key                int64          `json:"key"`
	ElementInstanceKey int64          `json:"element_instance_key"`
	ElementID          string         `json:"element_id"`
	ProcessInstanceKey int64          `json:"process_instance_key"`
	Type               string         `json:"type"`
	State              int64          `json:"state"`
	CreatedAt          int64          `json:"created_at"`
	Variables          string         `json:"variables"`
	ExecutionToken     int64          `json:"execution_token"`
	Assignee           sql.NullString `json:"assignee"`
	TotalCount         int64          `json:"total_count"`
}

// force sqlc to keep sort param
// workaround for sqlc does not replace params in order by
func (q *Queries) FindJobs(ctx context.Context, arg FindJobsParams) ([]FindJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, findJobs,
		arg.Sort,
		arg.Type,
		arg.State,
		arg.ProcessInstanceKey,
		arg.Assignee,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindJobsRow{}
	for rows.Next() {
		var i FindJobsRow
		if err := rows.Scan(
			&i.Key,
			&i.ElementInstanceKey,
			&i.ElementID,
			&i.ProcessInstanceKey,
			&i.Type,
			&i.State,
			&i.CreatedAt,
			&i.Variables,
			&i.ExecutionToken,
			&i.Assignee,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findProcessInstanceJobs = `-- name: FindProcessInstanceJobs :many
SELECT
    "key", element_instance_key, element_id, process_instance_key, type, state, created_at, variables, execution_token, assignee,
    COUNT(*) OVER () AS total_count
FROM
    job
WHERE
    process_instance_key = ?1
LIMIT ?3 OFFSET ?2
`

type FindProcessInstanceJobsParams struct {
	ProcessInstanceKey int64 `json:"process_instance_key"`
	Offset             int64 `json:"offset"`
	Size               int64 `json:"size"`
}

type FindProcessInstanceJobsRow struct {
	Key                int64          `json:"key"`
	ElementInstanceKey int64          `json:"element_instance_key"`
	ElementID          string         `json:"element_id"`
	ProcessInstanceKey int64          `json:"process_instance_key"`
	Type               string         `json:"type"`
	State              int64          `json:"state"`
	CreatedAt          int64          `json:"created_at"`
	Variables          string         `json:"variables"`
	ExecutionToken     int64          `json:"execution_token"`
	Assignee           sql.NullString `json:"assignee"`
	TotalCount         int64          `json:"total_count"`
}

func (q *Queries) FindProcessInstanceJobs(ctx context.Context, arg FindProcessInstanceJobsParams) ([]FindProcessInstanceJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, findProcessInstanceJobs, arg.ProcessInstanceKey, arg.Offset, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindProcessInstanceJobsRow{}
	for rows.Next() {
		var i FindProcessInstanceJobsRow
		if err := rows.Scan(
			&i.Key,
			&i.ElementInstanceKey,
			&i.ElementID,
			&i.ProcessInstanceKey,
			&i.Type,
			&i.State,
			&i.CreatedAt,
			&i.Variables,
			&i.ExecutionToken,
			&i.Assignee,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findProcessInstanceJobsInState = `-- name: FindProcessInstanceJobsInState :many
SELECT
    "key", element_instance_key, element_id, process_instance_key, type, state, created_at, variables, execution_token, assignee
FROM
    job
WHERE
    process_instance_key = ?1
    AND state IN (/*SLICE:states*/?)
`

type FindProcessInstanceJobsInStateParams struct {
	ProcessInstanceKey int64   `json:"process_instance_key"`
	States             []int64 `json:"states"`
}

func (q *Queries) FindProcessInstanceJobsInState(ctx context.Context, arg FindProcessInstanceJobsInStateParams) ([]Job, error) {
	query := findProcessInstanceJobsInState
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ProcessInstanceKey)
	if len(arg.States) > 0 {
		for _, v := range arg.States {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:states*/?", strings.Repeat(",?", len(arg.States))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:states*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.Key,
			&i.ElementInstanceKey,
			&i.ElementID,
			&i.ProcessInstanceKey,
			&i.Type,
			&i.State,
			&i.CreatedAt,
			&i.Variables,
			&i.ExecutionToken,
			&i.Assignee,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobsInStateByTokenKey = `-- name: GetJobsInStateByTokenKey :many

SELECT
    "key", element_instance_key, element_id, process_instance_key, type, state, created_at, variables, execution_token, assignee
FROM
    job
WHERE
    execution_token = ?1
    AND state IN (/*SLICE:states*/?)
`

type GetJobsInStateByTokenKeyParams struct {
	ExecutionTokenKey int64   `json:"execution_token_key"`
	States            []int64 `json:"states"`
}

// https://github.com/sqlc-dev/sqlc/issues/2452
func (q *Queries) GetJobsInStateByTokenKey(ctx context.Context, arg GetJobsInStateByTokenKeyParams) ([]Job, error) {
	query := getJobsInStateByTokenKey
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ExecutionTokenKey)
	if len(arg.States) > 0 {
		for _, v := range arg.States {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:states*/?", strings.Repeat(",?", len(arg.States))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:states*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.Key,
			&i.ElementInstanceKey,
			&i.ElementID,
			&i.ProcessInstanceKey,
			&i.Type,
			&i.State,
			&i.CreatedAt,
			&i.Variables,
			&i.ExecutionToken,
			&i.Assignee,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWaitingJobs = `-- name: GetWaitingJobs :many
SELECT
    "key", element_instance_key, element_id, process_instance_key, type, state, created_at, variables, execution_token, assignee
FROM
    job
WHERE
    state = 1
    AND type IN (/*SLICE:type*/?)
    AND key NOT IN (/*SLICE:key_skip*/?)
ORDER BY
    created_at ASC
LIMIT ?
`

type GetWaitingJobsParams struct {
	Type    []string `json:"type"`
	KeySkip []int64  `json:"key_skip"`
	Limit   int64    `json:"limit"`
}

func (q *Queries) GetWaitingJobs(ctx context.Context, arg GetWaitingJobsParams) ([]Job, error) {
	query := getWaitingJobs
	var queryParams []interface{}
	if len(arg.Type) > 0 {
		for _, v := range arg.Type {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:type*/?", strings.Repeat(",?", len(arg.Type))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:type*/?", "NULL", 1)
	}
	if len(arg.KeySkip) > 0 {
		for _, v := range arg.KeySkip {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:key_skip*/?", strings.Repeat(",?", len(arg.KeySkip))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:key_skip*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.Key,
			&i.ElementInstanceKey,
			&i.ElementID,
			&i.ProcessInstanceKey,
			&i.Type,
			&i.State,
			&i.CreatedAt,
			&i.Variables,
			&i.ExecutionToken,
			&i.Assignee,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveJob = `-- name: SaveJob :exec
INSERT INTO job(key, element_id, element_instance_key, process_instance_key, type, state, created_at, variables, execution_token, assignee)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT
    DO UPDATE SET
        state = excluded.state,
        variables = excluded.variables,
        assignee = excluded.assignee
`

type SaveJobParams struct {
	Key                int64          `json:"key"`
	ElementID          string         `json:"element_id"`
	ElementInstanceKey int64          `json:"element_instance_key"`
	ProcessInstanceKey int64          `json:"process_instance_key"`
	Type               string         `json:"type"`
	State              int64          `json:"state"`
	CreatedAt          int64          `json:"created_at"`
	Variables          string         `json:"variables"`
	ExecutionToken     int64          `json:"execution_token"`
	Assignee           sql.NullString `json:"assignee"`
}

func (q *Queries) SaveJob(ctx context.Context, arg SaveJobParams) error {
	_, err := q.db.ExecContext(ctx, saveJob,
		arg.Key,
		arg.ElementID,
		arg.ElementInstanceKey,
		arg.ProcessInstanceKey,
		arg.Type,
		arg.State,
		arg.CreatedAt,
		arg.Variables,
		arg.ExecutionToken,
		arg.Assignee,
	)
	return err
}
