// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.1
// source: zen_cluster.proto

package proto

import (
	context "context"
	proto "github.com/pbinitiative/zenbpm/internal/cluster/command/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZenService_Notify_FullMethodName                                = "/cluster.ZenService/Notify"
	ZenService_Join_FullMethodName                                  = "/cluster.ZenService/Join"
	ZenService_AddPartitionNode_FullMethodName                      = "/cluster.ZenService/AddPartitionNode"
	ZenService_ShutdownPartitionNode_FullMethodName                 = "/cluster.ZenService/ShutdownPartitionNode"
	ZenService_PartitionNodeLeaderChange_FullMethodName             = "/cluster.ZenService/PartitionNodeLeaderChange"
	ZenService_RemovePartitionNode_FullMethodName                   = "/cluster.ZenService/RemovePartitionNode"
	ZenService_ResumePartitionNode_FullMethodName                   = "/cluster.ZenService/ResumePartitionNode"
	ZenService_ClusterBackup_FullMethodName                         = "/cluster.ZenService/ClusterBackup"
	ZenService_ClusterRestore_FullMethodName                        = "/cluster.ZenService/ClusterRestore"
	ZenService_ConfigurationUpdate_FullMethodName                   = "/cluster.ZenService/ConfigurationUpdate"
	ZenService_AssignPartition_FullMethodName                       = "/cluster.ZenService/AssignPartition"
	ZenService_UnassignPartition_FullMethodName                     = "/cluster.ZenService/UnassignPartition"
	ZenService_PartitionBackup_FullMethodName                       = "/cluster.ZenService/PartitionBackup"
	ZenService_PartitionRestore_FullMethodName                      = "/cluster.ZenService/PartitionRestore"
	ZenService_StartPprofServer_FullMethodName                      = "/cluster.ZenService/StartPprofServer"
	ZenService_StopPprofServer_FullMethodName                       = "/cluster.ZenService/StopPprofServer"
	ZenService_NodeCommand_FullMethodName                           = "/cluster.ZenService/NodeCommand"
	ZenService_EvaluateDecision_FullMethodName                      = "/cluster.ZenService/EvaluateDecision"
	ZenService_DeployDmnResourceDefinition_FullMethodName           = "/cluster.ZenService/DeployDmnResourceDefinition"
	ZenService_DeployProcessDefinition_FullMethodName               = "/cluster.ZenService/DeployProcessDefinition"
	ZenService_ActivateJob_FullMethodName                           = "/cluster.ZenService/ActivateJob"
	ZenService_PublishMessage_FullMethodName                        = "/cluster.ZenService/PublishMessage"
	ZenService_SetMessageSubscriptionPointer_FullMethodName         = "/cluster.ZenService/SetMessageSubscriptionPointer"
	ZenService_FindActiveMessage_FullMethodName                     = "/cluster.ZenService/FindActiveMessage"
	ZenService_CreateInstance_FullMethodName                        = "/cluster.ZenService/CreateInstance"
	ZenService_StartProcessInstanceOnElements_FullMethodName        = "/cluster.ZenService/StartProcessInstanceOnElements"
	ZenService_ModifyProcessInstance_FullMethodName                 = "/cluster.ZenService/ModifyProcessInstance"
	ZenService_DeleteProcessInstanceVariable_FullMethodName         = "/cluster.ZenService/DeleteProcessInstanceVariable"
	ZenService_CancelProcessInstance_FullMethodName                 = "/cluster.ZenService/CancelProcessInstance"
	ZenService_GetProcessInstances_FullMethodName                   = "/cluster.ZenService/GetProcessInstances"
	ZenService_GetChildProcessInstances_FullMethodName              = "/cluster.ZenService/GetChildProcessInstances"
	ZenService_GetProcessInstance_FullMethodName                    = "/cluster.ZenService/GetProcessInstance"
	ZenService_GetProcessInstanceJobs_FullMethodName                = "/cluster.ZenService/GetProcessInstanceJobs"
	ZenService_GetDecisionInstance_FullMethodName                   = "/cluster.ZenService/GetDecisionInstance"
	ZenService_GetDecisionInstances_FullMethodName                  = "/cluster.ZenService/GetDecisionInstances"
	ZenService_GetJobs_FullMethodName                               = "/cluster.ZenService/GetJobs"
	ZenService_GetJob_FullMethodName                                = "/cluster.ZenService/GetJob"
	ZenService_GetFlowElementHistory_FullMethodName                 = "/cluster.ZenService/GetFlowElementHistory"
	ZenService_GetIncidents_FullMethodName                          = "/cluster.ZenService/GetIncidents"
	ZenService_ResolveIncident_FullMethodName                       = "/cluster.ZenService/ResolveIncident"
	ZenService_SubscribeJob_FullMethodName                          = "/cluster.ZenService/SubscribeJob"
	ZenService_CompleteJob_FullMethodName                           = "/cluster.ZenService/CompleteJob"
	ZenService_FailJob_FullMethodName                               = "/cluster.ZenService/FailJob"
	ZenService_ReassignJob_FullMethodName                           = "/cluster.ZenService/ReassignJob"
	ZenService_AssignJobToAssignee_FullMethodName                   = "/cluster.ZenService/AssignJobToAssignee"
	ZenService_GetProcessDefinitionStatistics_FullMethodName        = "/cluster.ZenService/GetProcessDefinitionStatistics"
	ZenService_GetProcessDefinitionElementStatistics_FullMethodName = "/cluster.ZenService/GetProcessDefinitionElementStatistics"
	ZenService_GetProcessInstanceElementStatistics_FullMethodName   = "/cluster.ZenService/GetProcessInstanceElementStatistics"
)

// ZenServiceClient is the client API for ZenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GRPC API exposed through private GRPC endpoint
type ZenServiceClient interface {
	// Notify notifies this node that a remote node is ready
	// for bootstrapping.
	Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
	// Join joins a remote node to the cluster.
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	// called by a partition leader when new node joins the cluster
	AddPartitionNode(ctx context.Context, in *AddPartitionNodeRequest, opts ...grpc.CallOption) (*AddPartitionNodeResponse, error)
	// called by a partition leader when node becomes unreachable
	ShutdownPartitionNode(ctx context.Context, in *ShutdownPartitionNodeRequest, opts ...grpc.CallOption) (*ShutdownPartitionNodeResponse, error)
	// called by a partition leader when he becomes a leader of partition cluster
	PartitionNodeLeaderChange(ctx context.Context, in *PartitionNodeLeaderChangeRequest, opts ...grpc.CallOption) (*PartitionNodeLeaderChangeResponse, error)
	// called by a partition leader when member node has to be reaped due to reap
	// settings
	RemovePartitionNode(ctx context.Context, in *RemovePartitionNodeRequest, opts ...grpc.CallOption) (*RemovePartitionNodeResponse, error)
	// called by a partition leader when member node becomes responsive after
	// being marked as shut down
	ResumePartitionNode(ctx context.Context, in *ResumePartitionNodeRequest, opts ...grpc.CallOption) (*ResumePartitionNodeResponse, error)
	ClusterBackup(ctx context.Context, in *ClusterBackupRequest, opts ...grpc.CallOption) (*ClusterBackupResponse, error)
	ClusterRestore(ctx context.Context, in *ClusterRestoreRequest, opts ...grpc.CallOption) (*ClusterRestoreResponse, error)
	ConfigurationUpdate(ctx context.Context, in *ConfigurationUpdateRequest, opts ...grpc.CallOption) (*ConfigurationUpdateResponse, error)
	AssignPartition(ctx context.Context, in *AssignPartitionRequest, opts ...grpc.CallOption) (*AssignPartitionResponse, error)
	UnassignPartition(ctx context.Context, in *UnassignPartitionRequest, opts ...grpc.CallOption) (*UnassignPartitionResponse, error)
	PartitionBackup(ctx context.Context, in *PartitionBackupRequest, opts ...grpc.CallOption) (*PartitionBackupResponse, error)
	PartitionRestore(ctx context.Context, in *PartitionRestoreRequest, opts ...grpc.CallOption) (*PartitionRestoreResponse, error)
	StartPprofServer(ctx context.Context, in *PprofServerRequest, opts ...grpc.CallOption) (*PprofServerStartResult, error)
	StopPprofServer(ctx context.Context, in *PprofServerRequest, opts ...grpc.CallOption) (*PprofServerStopResult, error)
	NodeCommand(ctx context.Context, in *proto.Command, opts ...grpc.CallOption) (*NodeCommandResponse, error)
	// engine endpoints
	// Deploys definition into partitions that receiving node is leader of
	EvaluateDecision(ctx context.Context, in *EvaluateDecisionRequest, opts ...grpc.CallOption) (*EvaluatedDRDResult, error)
	DeployDmnResourceDefinition(ctx context.Context, in *DeployDmnResourceDefinitionRequest, opts ...grpc.CallOption) (*DeployDmnResourceDefinitionResponse, error)
	DeployProcessDefinition(ctx context.Context, in *DeployProcessDefinitionRequest, opts ...grpc.CallOption) (*DeployProcessDefinitionResponse, error)
	ActivateJob(ctx context.Context, in *ActivateJobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActivateJobResponse], error)
	// PublishMessage requests a message publish on the engine running on a leader node of partition
	PublishMessage(ctx context.Context, in *PublishMessageRequest, opts ...grpc.CallOption) (*PublishMessageResponse, error)
	SetMessageSubscriptionPointer(ctx context.Context, in *SetMessageSubscriptionPointerRequest, opts ...grpc.CallOption) (*SetMessageSubscriptionPointerResponse, error)
	FindActiveMessage(ctx context.Context, in *FindActiveMessageRequest, opts ...grpc.CallOption) (*FindActiveMessageResponse, error)
	CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error)
	StartProcessInstanceOnElements(ctx context.Context, in *StartInstanceOnElementIdsRequest, opts ...grpc.CallOption) (*StartInstanceOnElementIdsResponse, error)
	ModifyProcessInstance(ctx context.Context, in *ModifyProcessInstanceRequest, opts ...grpc.CallOption) (*ModifyProcessInstanceResponse, error)
	DeleteProcessInstanceVariable(ctx context.Context, in *DeleteProcessInstanceVariableRequest, opts ...grpc.CallOption) (*DeleteProcessInstanceVariableResponse, error)
	CancelProcessInstance(ctx context.Context, in *CancelProcessInstanceRequest, opts ...grpc.CallOption) (*CancelProcessInstanceResponse, error)
	GetProcessInstances(ctx context.Context, in *GetProcessInstancesRequest, opts ...grpc.CallOption) (*GetProcessInstancesResponse, error)
	GetChildProcessInstances(ctx context.Context, in *GetChildProcessInstancesRequest, opts ...grpc.CallOption) (*GetChildProcessInstancesResponse, error)
	GetProcessInstance(ctx context.Context, in *GetProcessInstanceRequest, opts ...grpc.CallOption) (*GetProcessInstanceResponse, error)
	GetProcessInstanceJobs(ctx context.Context, in *GetProcessInstanceJobsRequest, opts ...grpc.CallOption) (*GetProcessInstanceJobsResponse, error)
	GetDecisionInstance(ctx context.Context, in *GetDecisionInstanceRequest, opts ...grpc.CallOption) (*GetDecisionInstanceResponse, error)
	GetDecisionInstances(ctx context.Context, in *GetDecisionInstancesRequest, opts ...grpc.CallOption) (*GetDecisionInstancesResponse, error)
	GetJobs(ctx context.Context, in *GetJobsRequest, opts ...grpc.CallOption) (*GetJobsResponse, error)
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
	GetFlowElementHistory(ctx context.Context, in *GetFlowElementHistoryRequest, opts ...grpc.CallOption) (*GetFlowElementHistoryResponse, error)
	GetIncidents(ctx context.Context, in *GetIncidentsRequest, opts ...grpc.CallOption) (*GetIncidentsResponse, error)
	ResolveIncident(ctx context.Context, in *ResolveIncidentRequest, opts ...grpc.CallOption) (*ResolveIncidentResponse, error)
	// Subscribes client to receive jobs of type
	SubscribeJob(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeJobRequest, SubscribeJobResponse], error)
	CompleteJob(ctx context.Context, in *CompleteJobRequest, opts ...grpc.CallOption) (*CompleteJobResponse, error)
	FailJob(ctx context.Context, in *FailJobRequest, opts ...grpc.CallOption) (*FailJobResponse, error)
	// Used by client to let server know that the job needs to be reassigned to another node
	ReassignJob(ctx context.Context, in *ReassignJobRequest, opts ...grpc.CallOption) (*ReassignJobResponse, error)
	AssignJobToAssignee(ctx context.Context, in *AssignJobToAssigneeRequest, opts ...grpc.CallOption) (*AssignJobToAssigneeResponse, error)
	GetProcessDefinitionStatistics(ctx context.Context, in *GetProcessDefinitionStatisticsRequest, opts ...grpc.CallOption) (*GetProcessDefinitionStatisticsResponse, error)
	GetProcessDefinitionElementStatistics(ctx context.Context, in *GetProcessDefinitionElementStatisticsRequest, opts ...grpc.CallOption) (*GetProcessDefinitionElementStatisticsResponse, error)
	GetProcessInstanceElementStatistics(ctx context.Context, in *GetProcessInstanceElementStatisticsRequest, opts ...grpc.CallOption) (*GetProcessInstanceElementStatisticsResponse, error)
}

type zenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZenServiceClient(cc grpc.ClientConnInterface) ZenServiceClient {
	return &zenServiceClient{cc}
}

func (c *zenServiceClient) Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyResponse)
	err := c.cc.Invoke(ctx, ZenService_Notify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, ZenService_Join_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) AddPartitionNode(ctx context.Context, in *AddPartitionNodeRequest, opts ...grpc.CallOption) (*AddPartitionNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPartitionNodeResponse)
	err := c.cc.Invoke(ctx, ZenService_AddPartitionNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) ShutdownPartitionNode(ctx context.Context, in *ShutdownPartitionNodeRequest, opts ...grpc.CallOption) (*ShutdownPartitionNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownPartitionNodeResponse)
	err := c.cc.Invoke(ctx, ZenService_ShutdownPartitionNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) PartitionNodeLeaderChange(ctx context.Context, in *PartitionNodeLeaderChangeRequest, opts ...grpc.CallOption) (*PartitionNodeLeaderChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartitionNodeLeaderChangeResponse)
	err := c.cc.Invoke(ctx, ZenService_PartitionNodeLeaderChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) RemovePartitionNode(ctx context.Context, in *RemovePartitionNodeRequest, opts ...grpc.CallOption) (*RemovePartitionNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemovePartitionNodeResponse)
	err := c.cc.Invoke(ctx, ZenService_RemovePartitionNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) ResumePartitionNode(ctx context.Context, in *ResumePartitionNodeRequest, opts ...grpc.CallOption) (*ResumePartitionNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumePartitionNodeResponse)
	err := c.cc.Invoke(ctx, ZenService_ResumePartitionNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) ClusterBackup(ctx context.Context, in *ClusterBackupRequest, opts ...grpc.CallOption) (*ClusterBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterBackupResponse)
	err := c.cc.Invoke(ctx, ZenService_ClusterBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) ClusterRestore(ctx context.Context, in *ClusterRestoreRequest, opts ...grpc.CallOption) (*ClusterRestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterRestoreResponse)
	err := c.cc.Invoke(ctx, ZenService_ClusterRestore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) ConfigurationUpdate(ctx context.Context, in *ConfigurationUpdateRequest, opts ...grpc.CallOption) (*ConfigurationUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigurationUpdateResponse)
	err := c.cc.Invoke(ctx, ZenService_ConfigurationUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) AssignPartition(ctx context.Context, in *AssignPartitionRequest, opts ...grpc.CallOption) (*AssignPartitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignPartitionResponse)
	err := c.cc.Invoke(ctx, ZenService_AssignPartition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) UnassignPartition(ctx context.Context, in *UnassignPartitionRequest, opts ...grpc.CallOption) (*UnassignPartitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnassignPartitionResponse)
	err := c.cc.Invoke(ctx, ZenService_UnassignPartition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) PartitionBackup(ctx context.Context, in *PartitionBackupRequest, opts ...grpc.CallOption) (*PartitionBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartitionBackupResponse)
	err := c.cc.Invoke(ctx, ZenService_PartitionBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) PartitionRestore(ctx context.Context, in *PartitionRestoreRequest, opts ...grpc.CallOption) (*PartitionRestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartitionRestoreResponse)
	err := c.cc.Invoke(ctx, ZenService_PartitionRestore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) StartPprofServer(ctx context.Context, in *PprofServerRequest, opts ...grpc.CallOption) (*PprofServerStartResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PprofServerStartResult)
	err := c.cc.Invoke(ctx, ZenService_StartPprofServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) StopPprofServer(ctx context.Context, in *PprofServerRequest, opts ...grpc.CallOption) (*PprofServerStopResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PprofServerStopResult)
	err := c.cc.Invoke(ctx, ZenService_StopPprofServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) NodeCommand(ctx context.Context, in *proto.Command, opts ...grpc.CallOption) (*NodeCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeCommandResponse)
	err := c.cc.Invoke(ctx, ZenService_NodeCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) EvaluateDecision(ctx context.Context, in *EvaluateDecisionRequest, opts ...grpc.CallOption) (*EvaluatedDRDResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluatedDRDResult)
	err := c.cc.Invoke(ctx, ZenService_EvaluateDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) DeployDmnResourceDefinition(ctx context.Context, in *DeployDmnResourceDefinitionRequest, opts ...grpc.CallOption) (*DeployDmnResourceDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployDmnResourceDefinitionResponse)
	err := c.cc.Invoke(ctx, ZenService_DeployDmnResourceDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) DeployProcessDefinition(ctx context.Context, in *DeployProcessDefinitionRequest, opts ...grpc.CallOption) (*DeployProcessDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployProcessDefinitionResponse)
	err := c.cc.Invoke(ctx, ZenService_DeployProcessDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) ActivateJob(ctx context.Context, in *ActivateJobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActivateJobResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ZenService_ServiceDesc.Streams[0], ZenService_ActivateJob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ActivateJobRequest, ActivateJobResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZenService_ActivateJobClient = grpc.ServerStreamingClient[ActivateJobResponse]

func (c *zenServiceClient) PublishMessage(ctx context.Context, in *PublishMessageRequest, opts ...grpc.CallOption) (*PublishMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishMessageResponse)
	err := c.cc.Invoke(ctx, ZenService_PublishMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) SetMessageSubscriptionPointer(ctx context.Context, in *SetMessageSubscriptionPointerRequest, opts ...grpc.CallOption) (*SetMessageSubscriptionPointerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetMessageSubscriptionPointerResponse)
	err := c.cc.Invoke(ctx, ZenService_SetMessageSubscriptionPointer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) FindActiveMessage(ctx context.Context, in *FindActiveMessageRequest, opts ...grpc.CallOption) (*FindActiveMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindActiveMessageResponse)
	err := c.cc.Invoke(ctx, ZenService_FindActiveMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInstanceResponse)
	err := c.cc.Invoke(ctx, ZenService_CreateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) StartProcessInstanceOnElements(ctx context.Context, in *StartInstanceOnElementIdsRequest, opts ...grpc.CallOption) (*StartInstanceOnElementIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartInstanceOnElementIdsResponse)
	err := c.cc.Invoke(ctx, ZenService_StartProcessInstanceOnElements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) ModifyProcessInstance(ctx context.Context, in *ModifyProcessInstanceRequest, opts ...grpc.CallOption) (*ModifyProcessInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifyProcessInstanceResponse)
	err := c.cc.Invoke(ctx, ZenService_ModifyProcessInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) DeleteProcessInstanceVariable(ctx context.Context, in *DeleteProcessInstanceVariableRequest, opts ...grpc.CallOption) (*DeleteProcessInstanceVariableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProcessInstanceVariableResponse)
	err := c.cc.Invoke(ctx, ZenService_DeleteProcessInstanceVariable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) CancelProcessInstance(ctx context.Context, in *CancelProcessInstanceRequest, opts ...grpc.CallOption) (*CancelProcessInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelProcessInstanceResponse)
	err := c.cc.Invoke(ctx, ZenService_CancelProcessInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) GetProcessInstances(ctx context.Context, in *GetProcessInstancesRequest, opts ...grpc.CallOption) (*GetProcessInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProcessInstancesResponse)
	err := c.cc.Invoke(ctx, ZenService_GetProcessInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) GetChildProcessInstances(ctx context.Context, in *GetChildProcessInstancesRequest, opts ...grpc.CallOption) (*GetChildProcessInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChildProcessInstancesResponse)
	err := c.cc.Invoke(ctx, ZenService_GetChildProcessInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) GetProcessInstance(ctx context.Context, in *GetProcessInstanceRequest, opts ...grpc.CallOption) (*GetProcessInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProcessInstanceResponse)
	err := c.cc.Invoke(ctx, ZenService_GetProcessInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) GetProcessInstanceJobs(ctx context.Context, in *GetProcessInstanceJobsRequest, opts ...grpc.CallOption) (*GetProcessInstanceJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProcessInstanceJobsResponse)
	err := c.cc.Invoke(ctx, ZenService_GetProcessInstanceJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) GetDecisionInstance(ctx context.Context, in *GetDecisionInstanceRequest, opts ...grpc.CallOption) (*GetDecisionInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDecisionInstanceResponse)
	err := c.cc.Invoke(ctx, ZenService_GetDecisionInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) GetDecisionInstances(ctx context.Context, in *GetDecisionInstancesRequest, opts ...grpc.CallOption) (*GetDecisionInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDecisionInstancesResponse)
	err := c.cc.Invoke(ctx, ZenService_GetDecisionInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) GetJobs(ctx context.Context, in *GetJobsRequest, opts ...grpc.CallOption) (*GetJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobsResponse)
	err := c.cc.Invoke(ctx, ZenService_GetJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, ZenService_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) GetFlowElementHistory(ctx context.Context, in *GetFlowElementHistoryRequest, opts ...grpc.CallOption) (*GetFlowElementHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFlowElementHistoryResponse)
	err := c.cc.Invoke(ctx, ZenService_GetFlowElementHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) GetIncidents(ctx context.Context, in *GetIncidentsRequest, opts ...grpc.CallOption) (*GetIncidentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIncidentsResponse)
	err := c.cc.Invoke(ctx, ZenService_GetIncidents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) ResolveIncident(ctx context.Context, in *ResolveIncidentRequest, opts ...grpc.CallOption) (*ResolveIncidentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveIncidentResponse)
	err := c.cc.Invoke(ctx, ZenService_ResolveIncident_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) SubscribeJob(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeJobRequest, SubscribeJobResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ZenService_ServiceDesc.Streams[1], ZenService_SubscribeJob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeJobRequest, SubscribeJobResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZenService_SubscribeJobClient = grpc.BidiStreamingClient[SubscribeJobRequest, SubscribeJobResponse]

func (c *zenServiceClient) CompleteJob(ctx context.Context, in *CompleteJobRequest, opts ...grpc.CallOption) (*CompleteJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteJobResponse)
	err := c.cc.Invoke(ctx, ZenService_CompleteJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) FailJob(ctx context.Context, in *FailJobRequest, opts ...grpc.CallOption) (*FailJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FailJobResponse)
	err := c.cc.Invoke(ctx, ZenService_FailJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) ReassignJob(ctx context.Context, in *ReassignJobRequest, opts ...grpc.CallOption) (*ReassignJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReassignJobResponse)
	err := c.cc.Invoke(ctx, ZenService_ReassignJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) AssignJobToAssignee(ctx context.Context, in *AssignJobToAssigneeRequest, opts ...grpc.CallOption) (*AssignJobToAssigneeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignJobToAssigneeResponse)
	err := c.cc.Invoke(ctx, ZenService_AssignJobToAssignee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) GetProcessDefinitionStatistics(ctx context.Context, in *GetProcessDefinitionStatisticsRequest, opts ...grpc.CallOption) (*GetProcessDefinitionStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProcessDefinitionStatisticsResponse)
	err := c.cc.Invoke(ctx, ZenService_GetProcessDefinitionStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) GetProcessDefinitionElementStatistics(ctx context.Context, in *GetProcessDefinitionElementStatisticsRequest, opts ...grpc.CallOption) (*GetProcessDefinitionElementStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProcessDefinitionElementStatisticsResponse)
	err := c.cc.Invoke(ctx, ZenService_GetProcessDefinitionElementStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zenServiceClient) GetProcessInstanceElementStatistics(ctx context.Context, in *GetProcessInstanceElementStatisticsRequest, opts ...grpc.CallOption) (*GetProcessInstanceElementStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProcessInstanceElementStatisticsResponse)
	err := c.cc.Invoke(ctx, ZenService_GetProcessInstanceElementStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZenServiceServer is the server API for ZenService service.
// All implementations must embed UnimplementedZenServiceServer
// for forward compatibility.
//
// GRPC API exposed through private GRPC endpoint
type ZenServiceServer interface {
	// Notify notifies this node that a remote node is ready
	// for bootstrapping.
	Notify(context.Context, *NotifyRequest) (*NotifyResponse, error)
	// Join joins a remote node to the cluster.
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	// called by a partition leader when new node joins the cluster
	AddPartitionNode(context.Context, *AddPartitionNodeRequest) (*AddPartitionNodeResponse, error)
	// called by a partition leader when node becomes unreachable
	ShutdownPartitionNode(context.Context, *ShutdownPartitionNodeRequest) (*ShutdownPartitionNodeResponse, error)
	// called by a partition leader when he becomes a leader of partition cluster
	PartitionNodeLeaderChange(context.Context, *PartitionNodeLeaderChangeRequest) (*PartitionNodeLeaderChangeResponse, error)
	// called by a partition leader when member node has to be reaped due to reap
	// settings
	RemovePartitionNode(context.Context, *RemovePartitionNodeRequest) (*RemovePartitionNodeResponse, error)
	// called by a partition leader when member node becomes responsive after
	// being marked as shut down
	ResumePartitionNode(context.Context, *ResumePartitionNodeRequest) (*ResumePartitionNodeResponse, error)
	ClusterBackup(context.Context, *ClusterBackupRequest) (*ClusterBackupResponse, error)
	ClusterRestore(context.Context, *ClusterRestoreRequest) (*ClusterRestoreResponse, error)
	ConfigurationUpdate(context.Context, *ConfigurationUpdateRequest) (*ConfigurationUpdateResponse, error)
	AssignPartition(context.Context, *AssignPartitionRequest) (*AssignPartitionResponse, error)
	UnassignPartition(context.Context, *UnassignPartitionRequest) (*UnassignPartitionResponse, error)
	PartitionBackup(context.Context, *PartitionBackupRequest) (*PartitionBackupResponse, error)
	PartitionRestore(context.Context, *PartitionRestoreRequest) (*PartitionRestoreResponse, error)
	StartPprofServer(context.Context, *PprofServerRequest) (*PprofServerStartResult, error)
	StopPprofServer(context.Context, *PprofServerRequest) (*PprofServerStopResult, error)
	NodeCommand(context.Context, *proto.Command) (*NodeCommandResponse, error)
	// engine endpoints
	// Deploys definition into partitions that receiving node is leader of
	EvaluateDecision(context.Context, *EvaluateDecisionRequest) (*EvaluatedDRDResult, error)
	DeployDmnResourceDefinition(context.Context, *DeployDmnResourceDefinitionRequest) (*DeployDmnResourceDefinitionResponse, error)
	DeployProcessDefinition(context.Context, *DeployProcessDefinitionRequest) (*DeployProcessDefinitionResponse, error)
	ActivateJob(*ActivateJobRequest, grpc.ServerStreamingServer[ActivateJobResponse]) error
	// PublishMessage requests a message publish on the engine running on a leader node of partition
	PublishMessage(context.Context, *PublishMessageRequest) (*PublishMessageResponse, error)
	SetMessageSubscriptionPointer(context.Context, *SetMessageSubscriptionPointerRequest) (*SetMessageSubscriptionPointerResponse, error)
	FindActiveMessage(context.Context, *FindActiveMessageRequest) (*FindActiveMessageResponse, error)
	CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error)
	StartProcessInstanceOnElements(context.Context, *StartInstanceOnElementIdsRequest) (*StartInstanceOnElementIdsResponse, error)
	ModifyProcessInstance(context.Context, *ModifyProcessInstanceRequest) (*ModifyProcessInstanceResponse, error)
	DeleteProcessInstanceVariable(context.Context, *DeleteProcessInstanceVariableRequest) (*DeleteProcessInstanceVariableResponse, error)
	CancelProcessInstance(context.Context, *CancelProcessInstanceRequest) (*CancelProcessInstanceResponse, error)
	GetProcessInstances(context.Context, *GetProcessInstancesRequest) (*GetProcessInstancesResponse, error)
	GetChildProcessInstances(context.Context, *GetChildProcessInstancesRequest) (*GetChildProcessInstancesResponse, error)
	GetProcessInstance(context.Context, *GetProcessInstanceRequest) (*GetProcessInstanceResponse, error)
	GetProcessInstanceJobs(context.Context, *GetProcessInstanceJobsRequest) (*GetProcessInstanceJobsResponse, error)
	GetDecisionInstance(context.Context, *GetDecisionInstanceRequest) (*GetDecisionInstanceResponse, error)
	GetDecisionInstances(context.Context, *GetDecisionInstancesRequest) (*GetDecisionInstancesResponse, error)
	GetJobs(context.Context, *GetJobsRequest) (*GetJobsResponse, error)
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	GetFlowElementHistory(context.Context, *GetFlowElementHistoryRequest) (*GetFlowElementHistoryResponse, error)
	GetIncidents(context.Context, *GetIncidentsRequest) (*GetIncidentsResponse, error)
	ResolveIncident(context.Context, *ResolveIncidentRequest) (*ResolveIncidentResponse, error)
	// Subscribes client to receive jobs of type
	SubscribeJob(grpc.BidiStreamingServer[SubscribeJobRequest, SubscribeJobResponse]) error
	CompleteJob(context.Context, *CompleteJobRequest) (*CompleteJobResponse, error)
	FailJob(context.Context, *FailJobRequest) (*FailJobResponse, error)
	// Used by client to let server know that the job needs to be reassigned to another node
	ReassignJob(context.Context, *ReassignJobRequest) (*ReassignJobResponse, error)
	AssignJobToAssignee(context.Context, *AssignJobToAssigneeRequest) (*AssignJobToAssigneeResponse, error)
	GetProcessDefinitionStatistics(context.Context, *GetProcessDefinitionStatisticsRequest) (*GetProcessDefinitionStatisticsResponse, error)
	GetProcessDefinitionElementStatistics(context.Context, *GetProcessDefinitionElementStatisticsRequest) (*GetProcessDefinitionElementStatisticsResponse, error)
	GetProcessInstanceElementStatistics(context.Context, *GetProcessInstanceElementStatisticsRequest) (*GetProcessInstanceElementStatisticsResponse, error)
	mustEmbedUnimplementedZenServiceServer()
}

// UnimplementedZenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZenServiceServer struct{}

func (UnimplementedZenServiceServer) Notify(context.Context, *NotifyRequest) (*NotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedZenServiceServer) Join(context.Context, *JoinRequest) (*JoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedZenServiceServer) AddPartitionNode(context.Context, *AddPartitionNodeRequest) (*AddPartitionNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPartitionNode not implemented")
}
func (UnimplementedZenServiceServer) ShutdownPartitionNode(context.Context, *ShutdownPartitionNodeRequest) (*ShutdownPartitionNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShutdownPartitionNode not implemented")
}
func (UnimplementedZenServiceServer) PartitionNodeLeaderChange(context.Context, *PartitionNodeLeaderChangeRequest) (*PartitionNodeLeaderChangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PartitionNodeLeaderChange not implemented")
}
func (UnimplementedZenServiceServer) RemovePartitionNode(context.Context, *RemovePartitionNodeRequest) (*RemovePartitionNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePartitionNode not implemented")
}
func (UnimplementedZenServiceServer) ResumePartitionNode(context.Context, *ResumePartitionNodeRequest) (*ResumePartitionNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumePartitionNode not implemented")
}
func (UnimplementedZenServiceServer) ClusterBackup(context.Context, *ClusterBackupRequest) (*ClusterBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterBackup not implemented")
}
func (UnimplementedZenServiceServer) ClusterRestore(context.Context, *ClusterRestoreRequest) (*ClusterRestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterRestore not implemented")
}
func (UnimplementedZenServiceServer) ConfigurationUpdate(context.Context, *ConfigurationUpdateRequest) (*ConfigurationUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigurationUpdate not implemented")
}
func (UnimplementedZenServiceServer) AssignPartition(context.Context, *AssignPartitionRequest) (*AssignPartitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignPartition not implemented")
}
func (UnimplementedZenServiceServer) UnassignPartition(context.Context, *UnassignPartitionRequest) (*UnassignPartitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnassignPartition not implemented")
}
func (UnimplementedZenServiceServer) PartitionBackup(context.Context, *PartitionBackupRequest) (*PartitionBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PartitionBackup not implemented")
}
func (UnimplementedZenServiceServer) PartitionRestore(context.Context, *PartitionRestoreRequest) (*PartitionRestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PartitionRestore not implemented")
}
func (UnimplementedZenServiceServer) StartPprofServer(context.Context, *PprofServerRequest) (*PprofServerStartResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartPprofServer not implemented")
}
func (UnimplementedZenServiceServer) StopPprofServer(context.Context, *PprofServerRequest) (*PprofServerStopResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopPprofServer not implemented")
}
func (UnimplementedZenServiceServer) NodeCommand(context.Context, *proto.Command) (*NodeCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeCommand not implemented")
}
func (UnimplementedZenServiceServer) EvaluateDecision(context.Context, *EvaluateDecisionRequest) (*EvaluatedDRDResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateDecision not implemented")
}
func (UnimplementedZenServiceServer) DeployDmnResourceDefinition(context.Context, *DeployDmnResourceDefinitionRequest) (*DeployDmnResourceDefinitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployDmnResourceDefinition not implemented")
}
func (UnimplementedZenServiceServer) DeployProcessDefinition(context.Context, *DeployProcessDefinitionRequest) (*DeployProcessDefinitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployProcessDefinition not implemented")
}
func (UnimplementedZenServiceServer) ActivateJob(*ActivateJobRequest, grpc.ServerStreamingServer[ActivateJobResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ActivateJob not implemented")
}
func (UnimplementedZenServiceServer) PublishMessage(context.Context, *PublishMessageRequest) (*PublishMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishMessage not implemented")
}
func (UnimplementedZenServiceServer) SetMessageSubscriptionPointer(context.Context, *SetMessageSubscriptionPointerRequest) (*SetMessageSubscriptionPointerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMessageSubscriptionPointer not implemented")
}
func (UnimplementedZenServiceServer) FindActiveMessage(context.Context, *FindActiveMessageRequest) (*FindActiveMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindActiveMessage not implemented")
}
func (UnimplementedZenServiceServer) CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInstance not implemented")
}
func (UnimplementedZenServiceServer) StartProcessInstanceOnElements(context.Context, *StartInstanceOnElementIdsRequest) (*StartInstanceOnElementIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartProcessInstanceOnElements not implemented")
}
func (UnimplementedZenServiceServer) ModifyProcessInstance(context.Context, *ModifyProcessInstanceRequest) (*ModifyProcessInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyProcessInstance not implemented")
}
func (UnimplementedZenServiceServer) DeleteProcessInstanceVariable(context.Context, *DeleteProcessInstanceVariableRequest) (*DeleteProcessInstanceVariableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProcessInstanceVariable not implemented")
}
func (UnimplementedZenServiceServer) CancelProcessInstance(context.Context, *CancelProcessInstanceRequest) (*CancelProcessInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelProcessInstance not implemented")
}
func (UnimplementedZenServiceServer) GetProcessInstances(context.Context, *GetProcessInstancesRequest) (*GetProcessInstancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProcessInstances not implemented")
}
func (UnimplementedZenServiceServer) GetChildProcessInstances(context.Context, *GetChildProcessInstancesRequest) (*GetChildProcessInstancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChildProcessInstances not implemented")
}
func (UnimplementedZenServiceServer) GetProcessInstance(context.Context, *GetProcessInstanceRequest) (*GetProcessInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProcessInstance not implemented")
}
func (UnimplementedZenServiceServer) GetProcessInstanceJobs(context.Context, *GetProcessInstanceJobsRequest) (*GetProcessInstanceJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProcessInstanceJobs not implemented")
}
func (UnimplementedZenServiceServer) GetDecisionInstance(context.Context, *GetDecisionInstanceRequest) (*GetDecisionInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDecisionInstance not implemented")
}
func (UnimplementedZenServiceServer) GetDecisionInstances(context.Context, *GetDecisionInstancesRequest) (*GetDecisionInstancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDecisionInstances not implemented")
}
func (UnimplementedZenServiceServer) GetJobs(context.Context, *GetJobsRequest) (*GetJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobs not implemented")
}
func (UnimplementedZenServiceServer) GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedZenServiceServer) GetFlowElementHistory(context.Context, *GetFlowElementHistoryRequest) (*GetFlowElementHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlowElementHistory not implemented")
}
func (UnimplementedZenServiceServer) GetIncidents(context.Context, *GetIncidentsRequest) (*GetIncidentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIncidents not implemented")
}
func (UnimplementedZenServiceServer) ResolveIncident(context.Context, *ResolveIncidentRequest) (*ResolveIncidentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveIncident not implemented")
}
func (UnimplementedZenServiceServer) SubscribeJob(grpc.BidiStreamingServer[SubscribeJobRequest, SubscribeJobResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeJob not implemented")
}
func (UnimplementedZenServiceServer) CompleteJob(context.Context, *CompleteJobRequest) (*CompleteJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteJob not implemented")
}
func (UnimplementedZenServiceServer) FailJob(context.Context, *FailJobRequest) (*FailJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FailJob not implemented")
}
func (UnimplementedZenServiceServer) ReassignJob(context.Context, *ReassignJobRequest) (*ReassignJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReassignJob not implemented")
}
func (UnimplementedZenServiceServer) AssignJobToAssignee(context.Context, *AssignJobToAssigneeRequest) (*AssignJobToAssigneeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignJobToAssignee not implemented")
}
func (UnimplementedZenServiceServer) GetProcessDefinitionStatistics(context.Context, *GetProcessDefinitionStatisticsRequest) (*GetProcessDefinitionStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProcessDefinitionStatistics not implemented")
}
func (UnimplementedZenServiceServer) GetProcessDefinitionElementStatistics(context.Context, *GetProcessDefinitionElementStatisticsRequest) (*GetProcessDefinitionElementStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProcessDefinitionElementStatistics not implemented")
}
func (UnimplementedZenServiceServer) GetProcessInstanceElementStatistics(context.Context, *GetProcessInstanceElementStatisticsRequest) (*GetProcessInstanceElementStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProcessInstanceElementStatistics not implemented")
}
func (UnimplementedZenServiceServer) mustEmbedUnimplementedZenServiceServer() {}
func (UnimplementedZenServiceServer) testEmbeddedByValue()                    {}

// UnsafeZenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZenServiceServer will
// result in compilation errors.
type UnsafeZenServiceServer interface {
	mustEmbedUnimplementedZenServiceServer()
}

func RegisterZenServiceServer(s grpc.ServiceRegistrar, srv ZenServiceServer) {
	// If the following call pancis, it indicates UnimplementedZenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZenService_ServiceDesc, srv)
}

func _ZenService_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_Notify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).Notify(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_AddPartitionNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPartitionNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).AddPartitionNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_AddPartitionNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).AddPartitionNode(ctx, req.(*AddPartitionNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_ShutdownPartitionNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownPartitionNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).ShutdownPartitionNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_ShutdownPartitionNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).ShutdownPartitionNode(ctx, req.(*ShutdownPartitionNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_PartitionNodeLeaderChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartitionNodeLeaderChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).PartitionNodeLeaderChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_PartitionNodeLeaderChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).PartitionNodeLeaderChange(ctx, req.(*PartitionNodeLeaderChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_RemovePartitionNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePartitionNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).RemovePartitionNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_RemovePartitionNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).RemovePartitionNode(ctx, req.(*RemovePartitionNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_ResumePartitionNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumePartitionNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).ResumePartitionNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_ResumePartitionNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).ResumePartitionNode(ctx, req.(*ResumePartitionNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_ClusterBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).ClusterBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_ClusterBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).ClusterBackup(ctx, req.(*ClusterBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_ClusterRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterRestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).ClusterRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_ClusterRestore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).ClusterRestore(ctx, req.(*ClusterRestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_ConfigurationUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigurationUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).ConfigurationUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_ConfigurationUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).ConfigurationUpdate(ctx, req.(*ConfigurationUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_AssignPartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignPartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).AssignPartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_AssignPartition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).AssignPartition(ctx, req.(*AssignPartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_UnassignPartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnassignPartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).UnassignPartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_UnassignPartition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).UnassignPartition(ctx, req.(*UnassignPartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_PartitionBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartitionBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).PartitionBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_PartitionBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).PartitionBackup(ctx, req.(*PartitionBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_PartitionRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartitionRestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).PartitionRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_PartitionRestore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).PartitionRestore(ctx, req.(*PartitionRestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_StartPprofServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PprofServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).StartPprofServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_StartPprofServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).StartPprofServer(ctx, req.(*PprofServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_StopPprofServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PprofServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).StopPprofServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_StopPprofServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).StopPprofServer(ctx, req.(*PprofServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_NodeCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).NodeCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_NodeCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).NodeCommand(ctx, req.(*proto.Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_EvaluateDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).EvaluateDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_EvaluateDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).EvaluateDecision(ctx, req.(*EvaluateDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_DeployDmnResourceDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployDmnResourceDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).DeployDmnResourceDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_DeployDmnResourceDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).DeployDmnResourceDefinition(ctx, req.(*DeployDmnResourceDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_DeployProcessDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployProcessDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).DeployProcessDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_DeployProcessDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).DeployProcessDefinition(ctx, req.(*DeployProcessDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_ActivateJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ActivateJobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ZenServiceServer).ActivateJob(m, &grpc.GenericServerStream[ActivateJobRequest, ActivateJobResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZenService_ActivateJobServer = grpc.ServerStreamingServer[ActivateJobResponse]

func _ZenService_PublishMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).PublishMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_PublishMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).PublishMessage(ctx, req.(*PublishMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_SetMessageSubscriptionPointer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMessageSubscriptionPointerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).SetMessageSubscriptionPointer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_SetMessageSubscriptionPointer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).SetMessageSubscriptionPointer(ctx, req.(*SetMessageSubscriptionPointerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_FindActiveMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindActiveMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).FindActiveMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_FindActiveMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).FindActiveMessage(ctx, req.(*FindActiveMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_CreateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).CreateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_CreateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).CreateInstance(ctx, req.(*CreateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_StartProcessInstanceOnElements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartInstanceOnElementIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).StartProcessInstanceOnElements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_StartProcessInstanceOnElements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).StartProcessInstanceOnElements(ctx, req.(*StartInstanceOnElementIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_ModifyProcessInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyProcessInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).ModifyProcessInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_ModifyProcessInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).ModifyProcessInstance(ctx, req.(*ModifyProcessInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_DeleteProcessInstanceVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProcessInstanceVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).DeleteProcessInstanceVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_DeleteProcessInstanceVariable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).DeleteProcessInstanceVariable(ctx, req.(*DeleteProcessInstanceVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_CancelProcessInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelProcessInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).CancelProcessInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_CancelProcessInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).CancelProcessInstance(ctx, req.(*CancelProcessInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_GetProcessInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProcessInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).GetProcessInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_GetProcessInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).GetProcessInstances(ctx, req.(*GetProcessInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_GetChildProcessInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChildProcessInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).GetChildProcessInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_GetChildProcessInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).GetChildProcessInstances(ctx, req.(*GetChildProcessInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_GetProcessInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProcessInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).GetProcessInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_GetProcessInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).GetProcessInstance(ctx, req.(*GetProcessInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_GetProcessInstanceJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProcessInstanceJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).GetProcessInstanceJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_GetProcessInstanceJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).GetProcessInstanceJobs(ctx, req.(*GetProcessInstanceJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_GetDecisionInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDecisionInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).GetDecisionInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_GetDecisionInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).GetDecisionInstance(ctx, req.(*GetDecisionInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_GetDecisionInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDecisionInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).GetDecisionInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_GetDecisionInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).GetDecisionInstances(ctx, req.(*GetDecisionInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_GetJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).GetJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_GetJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).GetJobs(ctx, req.(*GetJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_GetFlowElementHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlowElementHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).GetFlowElementHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_GetFlowElementHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).GetFlowElementHistory(ctx, req.(*GetFlowElementHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_GetIncidents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIncidentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).GetIncidents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_GetIncidents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).GetIncidents(ctx, req.(*GetIncidentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_ResolveIncident_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveIncidentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).ResolveIncident(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_ResolveIncident_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).ResolveIncident(ctx, req.(*ResolveIncidentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_SubscribeJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ZenServiceServer).SubscribeJob(&grpc.GenericServerStream[SubscribeJobRequest, SubscribeJobResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZenService_SubscribeJobServer = grpc.BidiStreamingServer[SubscribeJobRequest, SubscribeJobResponse]

func _ZenService_CompleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).CompleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_CompleteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).CompleteJob(ctx, req.(*CompleteJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_FailJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).FailJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_FailJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).FailJob(ctx, req.(*FailJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_ReassignJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReassignJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).ReassignJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_ReassignJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).ReassignJob(ctx, req.(*ReassignJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_AssignJobToAssignee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignJobToAssigneeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).AssignJobToAssignee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_AssignJobToAssignee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).AssignJobToAssignee(ctx, req.(*AssignJobToAssigneeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_GetProcessDefinitionStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProcessDefinitionStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).GetProcessDefinitionStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_GetProcessDefinitionStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).GetProcessDefinitionStatistics(ctx, req.(*GetProcessDefinitionStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_GetProcessDefinitionElementStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProcessDefinitionElementStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).GetProcessDefinitionElementStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_GetProcessDefinitionElementStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).GetProcessDefinitionElementStatistics(ctx, req.(*GetProcessDefinitionElementStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZenService_GetProcessInstanceElementStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProcessInstanceElementStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZenServiceServer).GetProcessInstanceElementStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZenService_GetProcessInstanceElementStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZenServiceServer).GetProcessInstanceElementStatistics(ctx, req.(*GetProcessInstanceElementStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZenService_ServiceDesc is the grpc.ServiceDesc for ZenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cluster.ZenService",
	HandlerType: (*ZenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _ZenService_Notify_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _ZenService_Join_Handler,
		},
		{
			MethodName: "AddPartitionNode",
			Handler:    _ZenService_AddPartitionNode_Handler,
		},
		{
			MethodName: "ShutdownPartitionNode",
			Handler:    _ZenService_ShutdownPartitionNode_Handler,
		},
		{
			MethodName: "PartitionNodeLeaderChange",
			Handler:    _ZenService_PartitionNodeLeaderChange_Handler,
		},
		{
			MethodName: "RemovePartitionNode",
			Handler:    _ZenService_RemovePartitionNode_Handler,
		},
		{
			MethodName: "ResumePartitionNode",
			Handler:    _ZenService_ResumePartitionNode_Handler,
		},
		{
			MethodName: "ClusterBackup",
			Handler:    _ZenService_ClusterBackup_Handler,
		},
		{
			MethodName: "ClusterRestore",
			Handler:    _ZenService_ClusterRestore_Handler,
		},
		{
			MethodName: "ConfigurationUpdate",
			Handler:    _ZenService_ConfigurationUpdate_Handler,
		},
		{
			MethodName: "AssignPartition",
			Handler:    _ZenService_AssignPartition_Handler,
		},
		{
			MethodName: "UnassignPartition",
			Handler:    _ZenService_UnassignPartition_Handler,
		},
		{
			MethodName: "PartitionBackup",
			Handler:    _ZenService_PartitionBackup_Handler,
		},
		{
			MethodName: "PartitionRestore",
			Handler:    _ZenService_PartitionRestore_Handler,
		},
		{
			MethodName: "StartPprofServer",
			Handler:    _ZenService_StartPprofServer_Handler,
		},
		{
			MethodName: "StopPprofServer",
			Handler:    _ZenService_StopPprofServer_Handler,
		},
		{
			MethodName: "NodeCommand",
			Handler:    _ZenService_NodeCommand_Handler,
		},
		{
			MethodName: "EvaluateDecision",
			Handler:    _ZenService_EvaluateDecision_Handler,
		},
		{
			MethodName: "DeployDmnResourceDefinition",
			Handler:    _ZenService_DeployDmnResourceDefinition_Handler,
		},
		{
			MethodName: "DeployProcessDefinition",
			Handler:    _ZenService_DeployProcessDefinition_Handler,
		},
		{
			MethodName: "PublishMessage",
			Handler:    _ZenService_PublishMessage_Handler,
		},
		{
			MethodName: "SetMessageSubscriptionPointer",
			Handler:    _ZenService_SetMessageSubscriptionPointer_Handler,
		},
		{
			MethodName: "FindActiveMessage",
			Handler:    _ZenService_FindActiveMessage_Handler,
		},
		{
			MethodName: "CreateInstance",
			Handler:    _ZenService_CreateInstance_Handler,
		},
		{
			MethodName: "StartProcessInstanceOnElements",
			Handler:    _ZenService_StartProcessInstanceOnElements_Handler,
		},
		{
			MethodName: "ModifyProcessInstance",
			Handler:    _ZenService_ModifyProcessInstance_Handler,
		},
		{
			MethodName: "DeleteProcessInstanceVariable",
			Handler:    _ZenService_DeleteProcessInstanceVariable_Handler,
		},
		{
			MethodName: "CancelProcessInstance",
			Handler:    _ZenService_CancelProcessInstance_Handler,
		},
		{
			MethodName: "GetProcessInstances",
			Handler:    _ZenService_GetProcessInstances_Handler,
		},
		{
			MethodName: "GetChildProcessInstances",
			Handler:    _ZenService_GetChildProcessInstances_Handler,
		},
		{
			MethodName: "GetProcessInstance",
			Handler:    _ZenService_GetProcessInstance_Handler,
		},
		{
			MethodName: "GetProcessInstanceJobs",
			Handler:    _ZenService_GetProcessInstanceJobs_Handler,
		},
		{
			MethodName: "GetDecisionInstance",
			Handler:    _ZenService_GetDecisionInstance_Handler,
		},
		{
			MethodName: "GetDecisionInstances",
			Handler:    _ZenService_GetDecisionInstances_Handler,
		},
		{
			MethodName: "GetJobs",
			Handler:    _ZenService_GetJobs_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _ZenService_GetJob_Handler,
		},
		{
			MethodName: "GetFlowElementHistory",
			Handler:    _ZenService_GetFlowElementHistory_Handler,
		},
		{
			MethodName: "GetIncidents",
			Handler:    _ZenService_GetIncidents_Handler,
		},
		{
			MethodName: "ResolveIncident",
			Handler:    _ZenService_ResolveIncident_Handler,
		},
		{
			MethodName: "CompleteJob",
			Handler:    _ZenService_CompleteJob_Handler,
		},
		{
			MethodName: "FailJob",
			Handler:    _ZenService_FailJob_Handler,
		},
		{
			MethodName: "ReassignJob",
			Handler:    _ZenService_ReassignJob_Handler,
		},
		{
			MethodName: "AssignJobToAssignee",
			Handler:    _ZenService_AssignJobToAssignee_Handler,
		},
		{
			MethodName: "GetProcessDefinitionStatistics",
			Handler:    _ZenService_GetProcessDefinitionStatistics_Handler,
		},
		{
			MethodName: "GetProcessDefinitionElementStatistics",
			Handler:    _ZenService_GetProcessDefinitionElementStatistics_Handler,
		},
		{
			MethodName: "GetProcessInstanceElementStatistics",
			Handler:    _ZenService_GetProcessInstanceElementStatistics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ActivateJob",
			Handler:       _ZenService_ActivateJob_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeJob",
			Handler:       _ZenService_SubscribeJob_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "zen_cluster.proto",
}
