replicaCount: 3 # Nên là số lẻ (3, 5) để thuật toán Raft hoạt động tốt

image:
  repository: ghcr.io/pbinitiative/zenbpm
  tag: "v1.1.0"
  pullPolicy: IfNotPresent

service:
  restPort: 8080
  grpcPort: 9090
  raftPort: 4001

persistence:
  enabled: true
  size: 5Gi
  accessMode: ReadWriteOnce

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

ingress:
  enabled: true
  className: "nginx" # Hoặc gce, traefik tùy cluster của mày
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: "qdrant-basic-auth"
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - Qdrant Dashboard"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

  hosts:
    - host: zenbpmdev.passiogolf.vn  # Domain mày muốn dùng
      paths:
        - path: /
          port: 8080
          pathType: Prefix
  tls:
    - secretName: passiogolfvn-tls
      hosts:
        - zenbpmdev.passiogolf.vn
